server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:library
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate.ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  main:
    allow-bean-definition-overriding=true:
